import { Icon } from "@iconify/react";
import { iconNames } from "../../utils/constants";
import { Tooltip } from "antd";

export const status = {
  loading: "loading",
  success: "success",
  error: "error",
  errorSameId: "errorSameId",
};
export const statusMessage = {
  error: "This file does not seem to be a transcript or degree plan (generated by this application)",
  errorSameId: "This student ID already exists",
};
export const getStatusIcon = (fileObj) => {
  const { error, loading, success, errorSameId } = status;
  if (fileObj.status === success) {
    return <Icon icon={iconNames.checkbox} className="icon orange small" />;
  } else if (fileObj.status === loading) {
    return <Icon icon={iconNames.loading} className="icon orange small" />;
  } else if (fileObj.status === error || fileObj.status == errorSameId || !fileObj.status) {
    if (!fileObj.status) fileObj.status = error;
    return (
      <Tooltip title={statusMessage[fileObj.status]}>
        <Icon icon={iconNames.redX} className="icon red small pointer" />
      </Tooltip>
    );
  }
};
