export const iconNames = {
  file: "ion:document-text-outline",
  checkbox: "material-symbols:check-circle-outline-rounded",
  redX: "ph:x-circle-bold",
  plus: "material-symbols:add-rounded",
  trash: "ph:trash-bold",
  checkboxMinus: "bxs:checkbox-minus",
  search: "ic:outline-search",
  import: "uil:import",
  zoomIn: "heroicons:magnifying-glass-plus-20-solid",
  zoomOut: "heroicons:magnifying-glass-minus-20-solid",
  threeDots: "ph:dots-three-vertical",
  close: "material-symbols:close",
};

export const pages = {
  homePage: "home-page",
  degreePlan: "degree-plan",
  pdfPreview: "pdf-preview",
  notFound: "not-found",
};

export const defaultSearchOptions = [
  { number: "CS6314", name: "WEB PROGRAMMING LANGUAGES" },
  { number: "CS6363", name: "DESIGN & ANALYS-COMP ALGORITHM" },
  { number: "CS6375", name: "MACHINE LEARNING" },
  { number: "CS6320", name: "NATURAL LANGUAGE PROCESSING" },
  { number: "CS6322", name: "INFORMATION RETRIEVAL" },
  { number: "CS6360", name: "DATABASE DESIGN" },
  { number: "CS6364", name: "ARTIFICIAL INTELLIGENCE" },
];

export const tableTypes = {
  core: 'core',
  following: 'following',
  electives: 'electives',
  prerequisites: 'prerequisites',
}
export const tableList = [ tableTypes.core, tableTypes.following, tableTypes.electives, tableTypes.prerequisites]
export const tableNames = {
  core: 'Core Courses',
  following: 'One of the Following Courses',
  electives: 'Approved 6000 Level Courses',
  prerequisites: 'Prerequisites',
}

export const tracks = [
  {
    label: "Data Science",
    key: "1",
  },
  {
    label: "Intelligent Systems",
    key: "2",
  },
  {
    label: "Interactive Computing",
    key: "3",
  },
  {
    label: "Networks and Telecommunication",
    key: "4",
  },
  {
    label: "Software Engineering",
    key: "5",
  },
  {
    label: "Systems",
    key: "6",
  },
  {
    label: "Traditional",
    key: "7",
  },
  {
    label: "Cyber Security",
    key: "8",
  },
];

export const genericStudent = {
  name: "Generic Student",
  studentId: 1111111,
  options: {
    fastTrack: false,
    thesis: false,
  },
  dates: {
    admitted: "21F",
    expected_graduation: "24S",
  },
  classes: [
    {
      name: "Statistical Methods for Data Sciences",
      number: "CS 6313",
      semester: "22S",
      transfer: "",
      grade: "A",
      attempted_credits: "",
      type: "core",
    },
    {
      name: "Big Data Management and Analytics",
      number: "CS 6350",
      semester: "22s",
      transfer: "",
      grade: "B+",
      attempted_credits: "",
      type: "core",
    },
    {
      name: "Design and Analysis of Computer Algorithms",
      number: "CS 6363",
      semester: "22s",
      transfer: "",
      grade: "A-",
      attempted_credits: "",
      type: "core",
    },
    {
      name: "Machine Learning",
      number: "CS 6375",
      semester: "21f",
      transfer: "",
      grade: "A",
      attempted_credits: "",
      type: "core",
    },
    {
      name: "Social Network Analytics",
      number: "CS 6301",
      semester: "22f",
      transfer: "",
      grade: "",
      attempted_credits: "",
      type: "following",
    },
    {
      name: "Natural Language Processing",
      number: "CS 6320",
      semester: "21f",
      transfer: "",
      grade: "",
      attempted_credits: "",
      type: "following",
    },
    {
      name: "Video Analytics",
      number: "CS 6327",
      semester: "",
      transfer: "",
      grade: "",
      attempted_credits: "",
      type: "following",
    },
    {
      name: "Statistics for Machine Learning",
      number: "CS 6347",
      semester: "",
      transfer: "",
      grade: "",
      attempted_credits: "",
      type: "following",
    },
    {
      name: "Database Design",
      number: "CS 6360",
      semester: "",
      transfer: "",
      grade: "A-",
      attempted_credits: "",
      type: "following",
    },
    {
      name: "Virtual Reality",
      number: "CS 6334",
      semester: "",
      transfer: "",
      grade: "B",
      attempted_credits: "",
      type: "electives",
    },
    {
      name: "Theory of Computation",
      number: "CS 6382",
      semester: "21f",
      transfer: "",
      grade: "A",
      attempted_credits: "",
      type: "electives",
    },
    {
      name: "Natural Language Processing",
      number: "CS 6320",
      semester: "22s",
      transfer: "",
      grade: "A",
      attempted_credits: "",
      type: "electives",
    },
    {
      name: "Network Security",
      number: "CS 6349",
      semester: "22f",
      transfer: "",
      grade: "",
      attempted_credits: "",
      type: "electives",
    },
    {
      name: "Sftwr Test/Validatn/Verificatn",
      number: "CS 6367",
      semester: "22f",
      transfer: "",
      grade: "",
      attempted_credits: "",
      type: "electives",
    },
    {
      name: "Software Maint Evolut & Re-Eng",
      number: "SE 6356",
      semester: "23s",
      transfer: "",
      grade: "",
      attempted_credits: "",
      type: "electives",
    },
    {
      name: "Computer Science I",
      number: "CS 5303",
      semester: "23s",
      transfer: "",
      grade: "",
      attempted_credits: "",
      type: "electives",
    },
    {
      name: "Computer Science II",
      number: "CS 5330",
      semester: "23s",
      transfer: "",
      grade: "",
      attempted_credits: "",
      type: "prerequisites",
    },
    {
      name: "Discrete Structures",
      number: "CS 5333",
      semester: "",
      transfer: "",
      grade: "",
      attempted_credits: "",
      type: "prerequisites",
    },
    {
      name: "Algorithm Analysis & Data Structures",
      number: "CS 5343",
      semester: "",
      transfer: "",
      grade: "",
      attempted_credits: "",
      type: "prerequisites",
    },
    {
      name: "Operating System Concepts",
      number: "CS 5348",
      semester: "",
      transfer: "",
      grade: "",
      attempted_credits: "",
      type: "prerequisites",
    },
    {
      name: "Probability & Statistics in CS<<",
      number: "CS 3341<<",
      semester: "",
      transfer: "",
      grade: "*** A- ***",
      attempted_credits: "",
      type: "prerequisites",
    },
  ],
  track: "Data Science",
};
